packages:
  - apps/*
  - packages/shared/*
  - packages/vue/*
  - packages/react/*
  - packages/tooling/*

catalog:
  "@nestjs/bullmq": ^11.0.4
  "@nestjs/cli": ^11.0.0
  "@nestjs/common": ^11.0.1
  "@nestjs/config": ^4.0.4
  "@nestjs/core": ^11.0.1
  "@nestjs/jwt": ^11.0.2
  "@nestjs/passport": ^11.0.5
  "@nestjs/platform-express": ^11.0.1
  "@nestjs/schematics": ^11.0.0
  "@nestjs/swagger": ^11.3.0
  "@nestjs/testing": ^11.0.1
  "@playwright/test": ^1.61.1
  "@prisma/adapter-mariadb": ^7.7.0
  "@prisma/client": ^7.7.0
  "@tailwindcss/vite": ^4.3.1
  "@testing-library/dom": ^10.4.1
  "@testing-library/jest-dom": ^6.9.1
  "@testing-library/react": ^16.3.0
  "@testing-library/vue": ^8.1.0
  "@types/express": ^5.0.0
  "@types/lodash": ^4.17.24
  "@types/node": ^24.10.1
  "@types/passport-jwt": ^4.0.1
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@types/supertest": ^7.0.0
  "@vitejs/plugin-react": ^6.0.3
  "@vitejs/plugin-vue": ^6.0.7
  "@vitest/coverage-v8": ^4.1.9
  "@vueuse/core": ^14.3.0
  ahooks: ^3.9.7
  bcryptjs: ^3.0.3
  bullmq: ^5.75.2
  class-transformer: ^0.5.1
  class-validator: ^0.15.1
  cross-env: ^10.1.0
  dotenv: ^16.4.5
  eslint-plugin-check-file: ^3.3.1
  express: ^5.1.0
  fast-glob: ^3.3.3
  happy-dom: ^20.0.11
  ioredis: ^5.10.1
  joi: ^18.1.2
  knip: ^6.20.0
  lodash: ^4.18.1
  mariadb: ^3.5.2
  passport: ^0.7.0
  passport-jwt: ^4.0.1
  pinia: ^3.0.4
  postcss-html: ^1.8.1
  prisma: ^7.7.0
  react: ^19.2.1
  react-dom: ^19.2.1
  react-router-dom: ^7.10.1
  reflect-metadata: ^0.2.2
  rollup-plugin-visualizer: ^7.0.1
  rxjs: ^7.8.1
  sass-embedded: ^1.100.0
  snowflake-id: ^1.1.0
  stylelint: ^17.13.0
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^40.0.0
  stylelint-config-standard-scss: ^17.0.0
  supertest: ^7.0.0
  tailwindcss: ^4.3.1
  tsc-watch: ^7.2.0
  tsx: ^4.21.0
  typescript: "6.0.3"
  validate-npm-package-name: ^7.0.2
  vitest: ^4.1.9
  vue: ^3.5.25
  vue-router: ^4.6.3
  vue-tsc: ^3.1.5
  yaml: ^2.9.0
  zustand: ^5.0.9
